name:                fire-json-solution
version:             0.1.0.0
github:              "fraser-dunlop/fire-json-solution"
license:             BSD3
author:              "Fraser Dunlop"
maintainer:          "frjd2@st-andrews.ac.uk"
copyright:           "2019 Fraser Dunlop"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fire-json-solution#readme>

dependencies:
- base >= 4.7 && < 5
- shelly
- json
- text

library:
  source-dirs: src

executables:
  fire-json-solution:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fire-json-solution

tests:
  fire-json-solution-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fire-json-solution
